spring.application.name=MarketplaceService
spring.data.mongodb.uri=mongodb+srv://pallavivangari:Squad%40123@cluster0.mkepx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Products
server.port=8070

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.data.mongodb.auto-index-creation=true

logging.level.org.springdoc=INFO

# Kafka settings
spring.kafka.bootstrap-servers=kafka:9093
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG

# Enable Prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.prometheus.metrics.export.enabled=true

# Customize actuator base path if needed
management.endpoints.web.base-path=/actuator

# Zipkin URL inside Docker network
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
