spring.application.name=FeedService
server.port=8095

# Kafka Config
spring.kafka.bootstrap-servers=kafka:9093
spring.kafka.consumer.group-id=feed-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.listener.concurrency=3

# Redis Config
spring.data.redis.host=redis-11929.c325.us-east-1-4.ec2.redns.redis-cloud.com
spring.data.redis.port=11929
spring.data.redis.password=caqPK21PEZ9V6oAykptOJJsOroOxKd86
spring.data.redis.ssl.enabled=true


spring.data.mongodb.uri=mongodb+srv://pallavivangari:Squad%40123@cluster0.mkepx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=FeedPostsAndFollowers
spring.data.mongodb.auto-index-creation=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Enable Prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.prometheus.metrics.export.enabled=true

# Customize actuator base path if needed
management.endpoints.web.base-path=/actuator

# Zipkin URL inside Docker network
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.endpoints.web.base-path=/actuator
